### ISSUE TITLE
FizzBuzz - Resultado errado

### ISSUE THREAD

**Issue by ricardonunesdev** [alexandrebatista84/python-exercises#1]
Se correres o código vais ver que o resultado não está certo.

No 15 devia escrever `fizzbuzz` e só escreve `fizz`, o mesmo acontece para os outros múltiplos de 3 e 5.

Parte do output:
```
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizz (devia ser fizzbuzz)
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizz (devia ser fizzbuzz)
31
32
fizz
34
buzz
fizz
37
38
fizz
buzz
41
fizz
43
44
fizz (devia ser fizzbuzz)
46
47
fizz
49
buzz
```

Tens um problema de prioridade no código (dica), simples de resolver ;)

**Comment by alexandrebatista84** [comment]
Fizzbuzz já foi corrigido e optimizado @ricardonunesdev

**Comment by ricardonunesdev** [comment]
Parece-me bem ;)
